[project]
authors = [
    {name = "Neuron Grid", email = "neuron-grid@neuron-grid.net"}
]

version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "graphviz"
]